version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env

  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: